# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20161020_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatefile',
            name='arquivo',
            field=models.FileField(upload_to=''),
        ),
    ]
