# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20161021_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatefile',
            name='arquivo',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
