# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20161021_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefile',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='templatefile',
            name='arquivo',
            field=models.FileField(upload_to='product/%Y/%m/%d'),
        ),
    ]
