# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20161021_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatefile',
            name='descricao',
            field=models.TextField(max_length=100),
        ),
    ]
